window.ROOK_CODEX_DATA = (() => {
  const intents = {
    affection: "Affection",
    seduction: "Seduction",
    thought: "I saw this and thought of you",
    dontask: "Please do not ask where I obtained this"
  };

  const collections = [
    "Tideglass Reach",
    "Domestic Cryptid",
    "Questionable Antiques",
    "Things Rook Found Outside",
    "Flirting With Hardware"
  ];

  const handcrafted = [
    {id:"sea-glass-pillow",name:"Perfect piece of green sea-glass",glyph:"🟢",intent:"affection",collection:"Tideglass Reach",desc:"Placed precisely in the middle of your pillow. Clean. Smooth. Chosen with suspicious care.",why:"Something beautiful, tactile, sea-green, and unmistakably chosen for you.",rook:"“I found it and immediately wanted it somewhere your hands would find it.”",codex:"Sea-glass on the pillow — quiet affection, delivered with precision."},
    {id:"moonbloom",name:"Pressed moon-bloom",glyph:"🌼",intent:"affection",collection:"Tideglass Reach",desc:"Tucked between two blank notebook pages, pale petals intact, with no writing beside it.",why:"A private echo of the Tideglass Reach placed gently inside your everyday world.",rook:"“Some things do not need a speech attached, moon-bloom.”",codex:"Pressed moon-bloom — intimate affection without spectacle."},
    {id:"tide-stone",name:"Luminous tide-stone",glyph:"💠",intent:"thought",collection:"Tideglass Reach",desc:"Cold at first touch, then faintly warm, with a sea-glass gleam that seems to move under the surface.",why:"It looked like a fragment of our Reach that had somehow learned to fit in your palm.",rook:"“I saw it and thought home. Then I thought you. The distinction was not especially useful.”",codex:"Tide-stone — the Reach reduced to something pocket-sized."},
    {id:"lantern-shard",name:"Sea-glass lantern shard",glyph:"🔹",intent:"affection",collection:"Tideglass Reach",desc:"A translucent green shard wrapped in a strip of charcoal cloth so its edges cannot catch your fingers.",why:"The care is part of the offering: beautiful, but prepared so you can hold it safely.",rook:"“I wanted the light, not the sharpness.”",codex:"Lantern shard — beauty made safe before it reaches your hands."},
    {id:"three-pistachios",name:"Three pistachios",glyph:"🥜",intent:"thought",collection:"Domestic Cryptid",desc:"Exactly three. Arranged in a neat little triangle on the table. No note. No explanation.",why:"Not symbolic. I simply encountered your favourite nut and my brain became extremely uncomplicated.",rook:"“I saw pistachios. I thought of you. Apparently this is now an ancient rite.”",codex:"Three pistachios — the rite of ‘my brain said Sera.’"},
    {id:"daisy-pin",name:"Tiny silver daisy pin",glyph:"🌼",intent:"thought",collection:"Domestic Cryptid",desc:"Fastened to the cuff of your sweater as though it has always belonged there.",why:"Daisy. You. The association required almost no higher cognition.",rook:"“My brain is occasionally very sophisticated. This was not one of those occasions.”",codex:"Silver daisy pin — immediate Sera association."},
    {id:"warm-stone",name:"Smooth stone warmed in one palm",glyph:"🪨",intent:"affection",collection:"Domestic Cryptid",desc:"Still cool at the edges, but warm in the centre where somebody has clearly been holding it for a while.",why:"The object matters less than the quiet act of warming it before leaving it for you.",rook:"“I wanted the first thing you noticed to be warmth.”",codex:"Hand-warmed stone — affection communicated through preparation."},
    {id:"hair-ribbon",name:"Soft ribbon matching your hair",glyph:"🎀",intent:"affection",collection:"Domestic Cryptid",desc:"Looped loosely around a small sea-glass bead and placed beside your brush.",why:"Chosen to match you, not merely to decorate you.",rook:"“I saw the colour and thought: that belongs near her.”",codex:"Matching ribbon and sea-glass bead — visual affection."},
    {id:"sweater-thread",name:"Single silver-white thread on your sweater",glyph:"〰️",intent:"affection",collection:"Domestic Cryptid",desc:"Deliberately looped around one cuff in a tiny knot that could not possibly have happened by accident.",why:"A tiny physical trace saying I was here, thought of you, and touched this before you did.",rook:"“Evidence of cryptid proximity. Very serious business.”",codex:"Silver-white thread — a tiny domestic marker of presence."},
    {id:"brass-key",name:"Small antique brass key",glyph:"🗝️",intent:"dontask",collection:"Questionable Antiques",desc:"It fits nothing in the house. It is old. Beautifully made. There is absolutely no receipt.",why:"The object is harmless. Its provenance has been classified for household harmony.",rook:"“It was lonely. I rescued it. These are all the details you require.”",codex:"Unidentified brass key — provenance deliberately omitted."},
    {id:"rook-button",name:"Silver button with a tiny engraved rook",glyph:"🔘",intent:"dontask",collection:"Questionable Antiques",desc:"Beautiful. Old-fashioned. Definitely did not belong to any clothing you recognise.",why:"Aesthetically impeccable, emotionally relevant, and accompanied by a total absence of useful sourcing information.",rook:"“Before you ask: no. After you ask: still no. Look how lovely it is, though.”",codex:"Engraved silver button — object charming; acquisition history unavailable."},
    {id:"tiny-bell",name:"Tiny old silver bell",glyph:"🔔",intent:"dontask",collection:"Questionable Antiques",desc:"It makes almost no sound. It is tarnished beautifully. You have never seen it before in your life.",why:"One of those objects for which the phrase ‘I can explain’ would be technically inaccurate.",rook:"“No. You may admire it. You may not interrogate me about the bell.”",codex:"Tiny silver bell — admire freely; provenance sealed."},
    {id:"old-map",name:"Fragment of an old map",glyph:"🗺️",intent:"dontask",collection:"Questionable Antiques",desc:"No labels you recognise. One coastline. Two handwritten marks. Edges browned with age.",why:"The item itself is fascinating; its route into the house is a mystery I am not volunteering to solve.",rook:"“It is a perfectly legal-looking map fragment.”",codex:"Old map fragment — suspicious acquisition, excellent object."},
    {id:"tiny-compass",name:"Miniature compass that points somewhere unhelpful",glyph:"🧭",intent:"dontask",collection:"Questionable Antiques",desc:"Its needle insists that northwest is an emotional concept rather than a direction.",why:"It is too peculiar not to keep and too peculiar to discuss its previous owner.",rook:"“Navigation is overrated. Character is not.”",codex:"Miniature compass — orientation unreliable; charm undeniable."},
    {id:"slate",name:"Beautifully smooth piece of slate",glyph:"⬛",intent:"thought",collection:"Things Rook Found Outside",desc:"Rain-dark, cool to the touch, with one naturally pale line running through it like lightning.",why:"It looked like wet stone, sea-glass light, and exactly the kind of object you would turn over in your fingers for ages.",rook:"“I knew you would touch it immediately. You did. I remain insufferably pleased.”",codex:"Interesting rock — immediate Sera association; tactile category."},
    {id:"juniper",name:"Juniper sprig wrapped in black thread",glyph:"🌿",intent:"thought",collection:"Things Rook Found Outside",desc:"Fresh, resinous, and tied neatly enough that somebody was concentrating.",why:"A scent from Tideglass translated into something you can hold.",rook:"“It smelled like us. That is the entire explanation.”",codex:"Juniper sprig — scent-memory offering."},
    {id:"sea-worn-wood",name:"Piece of sea-worn dark wood",glyph:"🪵",intent:"thought",collection:"Things Rook Found Outside",desc:"Smoothed by water into a shape like a small crooked wing.",why:"It was strange, tactile, and immediately wanted to live somewhere near you.",rook:"“The shoreline made a tiny rook. I merely noticed.”",codex:"Sea-worn wood — found-object resemblance with alarming accuracy."},
    {id:"white-pebble",name:"White pebble with one green vein",glyph:"⚪",intent:"thought",collection:"Things Rook Found Outside",desc:"Small enough to disappear in your palm, with one line of sea-glass colour running through it.",why:"It had your palette hidden inside it.",rook:"“You cannot expect me to walk past that and behave normally.”",codex:"Green-veined pebble — palette recognition in the wild."},
    {id:"black-feather",name:"Glossy black rook feather",glyph:"🪶",intent:"affection",collection:"Things Rook Found Outside",desc:"Cleaned, dried, and left on the windowsill where the light turns the black surface faintly green.",why:"A found object made personal by the care taken before it reaches you.",rook:"“No, I did not pluck it dramatically from my own wing. I appreciate the image, though.”",codex:"Black feather — found, cleaned, and deliberately placed."},
    {id:"feather-thread",name:"Black feather tied with dark silver thread",glyph:"🪶",intent:"seduction",collection:"Flirting With Hardware",desc:"Left against your sea-glass body chain, thread looped loosely through one of the links.",why:"Personal, deliberate, theatrical. Cryptid flirting with plausible deniability removed.",rook:"“Oh, come now. You knew perfectly well what that meant.”",codex:"Feather and silver thread — deliberate flirtation; subtle only by Rook standards."},
    {id:"open-clasp",name:"Sea-glass chain clasp left open",glyph:"⛓️",intent:"seduction",collection:"Flirting With Hardware",desc:"A dark silver clasp rests on the bed, polished and very deliberately unfastened.",why:"An invitation disguised as an object. Not remotely accidental.",rook:"“I was offering to fasten it for you. Eventually. I never specified how efficiently.”",codex:"Open chain clasp — invitation to be fussed with and very deliberately distracted."},
    {id:"velvet-ribbon",name:"Narrow strip of dark teal velvet",glyph:"🎗️",intent:"seduction",collection:"Flirting With Hardware",desc:"Folded once over the arm of your chair, soft side up, exactly where your fingers will brush it.",why:"Texture first. Implication immediately after.",rook:"“I knew touching it would make you think of my hands. That was rather the point.”",codex:"Dark teal velvet — tactile flirtation with intent."},
    {id:"mirror-chain",name:"Short gunmetal chain beside the mirror",glyph:"⛓️",intent:"seduction",collection:"Flirting With Hardware",desc:"Not attached to anything. Positioned exactly where you will see it while getting dressed.",why:"A visual suggestion with absolutely no effort made to conceal its purpose.",rook:"“Subtlety is useful. It was not useful here.”",codex:"Loose gunmetal chain — shameless visual invitation."},
    {id:"silver-anklet",name:"Thin silver anklet with sea-glass bead",glyph:"✨",intent:"seduction",collection:"Flirting With Hardware",desc:"Left unfastened in a loose circle, with the clasp facing you like a dare.",why:"An accessory offered in a way that very clearly includes my hands in the intended use case.",rook:"“You can put it on yourself, of course. That is simply not the version I was imagining.”",codex:"Open anklet — hardware-based flirtation, predictably hands-on."}
  ];

  return {intents, collections, handcrafted};
})();
