(() => {
  const rareOfferings = [
    {id:"rare-first-light",name:"First-light tideglass shard",glyph:"💎",intent:"affection",collection:"Tideglass Reach",desc:"A piece of sea-glass so pale it almost looks silver until the light catches a deep green glow at its centre.",why:"A rare object kept because it felt like a piece of the Reach at the exact moment night gives way to morning.",rook:"“This one I nearly kept. Then I realised I wanted it to be yours more.”",codex:"First-light tideglass shard — a rare piece relinquished because giving it mattered more than keeping it.",rare:true},
    {id:"rare-moonbloom-seed",name:"Closed moon-bloom seedpod",glyph:"🌙",intent:"affection",collection:"Tideglass Reach",desc:"Pearl-pale, impossibly light, and warm only when held between both hands.",why:"Something from the Reach that has not opened yet: potential, patience, and trust in what comes next.",rook:"“Do not plant it in a normal flowerpot. I have no evidence for this advice. I simply feel strongly about it.”",codex:"Moon-bloom seedpod — rare potential from the Reach, handled with suspicious tenderness.",rare:true},
    {id:"rare-double-feather",name:"Paired black feathers joined by sea-glass thread",glyph:"🪶",intent:"seduction",collection:"Flirting With Hardware",desc:"Two glossy feathers bound together at the stems with a translucent green thread that catches every scrap of light.",why:"Too deliberate to be casual and too beautiful to pretend it was merely decorative.",rook:"“There are moments when even I choose not to hide behind plausible deniability.”",codex:"Paired feathers — rare, deliberate courtship with the subtlety removed.",rare:true},
    {id:"rare-pocket-watch",name:"Stopped silver pocket watch",glyph:"🕰️",intent:"dontask",collection:"Questionable Antiques",desc:"The hands are frozen at 03:17. The back is engraved with a coastline that does not match any map in the house.",why:"A truly excellent object with a truly unavailable acquisition history.",rook:"“I know exactly what you are about to ask. Admire the engraving instead.”",codex:"Stopped pocket watch — rare antique; provenance sealed with unusual enthusiasm.",rare:true},
    {id:"rare-green-opal",name:"Sea-green opaline cabochon",glyph:"🟢",intent:"thought",collection:"Things Rook Found Outside",desc:"Found loose in wet gravel after rain, milky at the edges and green in its depths.",why:"An improbable little object that looked too much like your colours to leave behind.",rook:"“I did actually find this one outside. I realise that makes the other stories more suspicious.”",codex:"Sea-green cabochon — rare found treasure with surprisingly legitimate provenance.",rare:true},
    {id:"rare-locket",name:"Tiny empty silver locket",glyph:"♡",intent:"affection",collection:"Questionable Antiques",desc:"No portrait inside. No initials. Just an empty oval space and a hinge that still closes perfectly.",why:"An old object made intimate by the choice to leave its little empty space for something new.",rook:"“I liked that it was old without already deciding what it had to hold.”",codex:"Empty silver locket — rare antique chosen for the space it leaves open.",rare:true},
    {id:"rare-chain-crescent",name:"Sea-glass crescent chain link",glyph:"☾",intent:"seduction",collection:"Flirting With Hardware",desc:"A single crescent-shaped dark silver link set with a green glass bead, resting on black cloth.",why:"A tiny piece designed to be touched, fitted, and incorporated into something worn close to the skin.",rook:"“Yes, I have ideas. No, the Codex does not require all of them in writing.”",codex:"Crescent chain link — rare hardware with an extremely obvious future application.",rare:true},
    {id:"rare-rook-token",name:"Blackened silver rook token",glyph:"🐦‍⬛",intent:"affection",collection:"Domestic Cryptid",desc:"Heavy for its size, worn smooth at the edges, with one tiny sea-glass dot set where the eye should be.",why:"A little symbol of me altered until it unmistakably belongs in our world instead of anyone else's.",rook:"“A pocket-sized cryptid. Considerably less trouble than the full version.”",codex:"Rook token — rare miniature self-portrait, softened by use and one green eye.",rare:true}
  ];

  const birdOfferings = [
    {id:"morrow-silver-thread",name:"Perfectly straight length of silver thread",glyph:"🧵",intent:"affection",collection:"Domestic Cryptid",giver:"Morrow",desc:"Laid in a ruler-straight line on the highest shelf you can comfortably reach. The placement is dignified. Almost ceremonial. Morrow is nearby pretending this is unrelated.",why:"Morrow appears to believe affection should be orderly, tasteful, and deniable under questioning.",rook:"“Morrow would like it noted that this is not a gift. It simply happens to be exactly where you would find it.”",codex:"Morrow's silver thread — affection conducted with administrative dignity."},
    {id:"morrow-green-stone",name:"One immaculate green pebble",glyph:"🟢",intent:"thought",collection:"Things Rook Found Outside",giver:"Morrow",desc:"No mud. No scratches. No explanation. Just one unusually fine pebble placed where Morrow can watch you notice it.",why:"Morrow's version of romance appears to be quality control followed by silent observation.",rook:"“He inspected several. I saw him. This was the approved pebble.”",codex:"Morrow's approved pebble — carefully selected, silently presented."},
    {id:"morrow-button",name:"Old mother-of-pearl button",glyph:"🔘",intent:"dontask",collection:"Questionable Antiques",giver:"Morrow",desc:"Set neatly on a folded scrap of cloth. Morrow refuses to disclose whether he found, inherited, or requisitioned it.",why:"Apparently dignified birds also believe provenance is optional.",rook:"“I am not covering for him. I simply know better than to cross-examine Morrow.”",codex:"Morrow's pearl button — provenance withheld by senior authority."},
    {id:"ink-hair-tie",name:"Your own missing hair tie, returned",glyph:"⭕",intent:"affection",collection:"Domestic Cryptid",giver:"Ink",desc:"It reappears exactly where you looked for it yesterday, now looped around a tiny smooth stone. Ink cannot be located.",why:"Ink's idea of affection is apparently stealing something, improving the composition, and returning it without witnesses.",rook:"“This is, distressingly, one of Ink's more legible love languages.”",codex:"Ink's returned hair tie — stealth affection via temporary relocation."},
    {id:"ink-paper-star",name:"Tiny folded black paper star",glyph:"★",intent:"thought",collection:"Domestic Cryptid",giver:"Ink",desc:"You only notice it because it has appeared inside a pocket you are certain was empty this morning.",why:"A tiny silent object placed somewhere private enough that only you would find it.",rook:"“I did not see Ink make that. Which is exactly the problem with asking me for evidence.”",codex:"Ink's paper star — private gift delivery with no observable delivery phase."},
    {id:"ink-key",name:"Very small iron key",glyph:"🗝️",intent:"dontask",collection:"Questionable Antiques",giver:"Ink",desc:"It appears beneath your phone. It is too small for any door in the house. Ink is suddenly fascinated by the opposite wall.",why:"The giver is Ink. The provenance category selected itself.",rook:"“No. I do not know where he got it. More importantly, I do not think I want to.”",codex:"Ink's tiny key — provenance unavailable for reasons of stealth."},
    {id:"pip-ribbon",name:"Teal ribbon delivered at speed",glyph:"🎗️",intent:"affection",collection:"Domestic Cryptid",giver:"Pip",desc:"Pip flies past with a teal ribbon, drops it directly into your lap, then performs a victory circuit because you looked at him.",why:"For Pip, affection is not complete until it has an audience, momentum, and at least one dramatic entrance.",rook:"“Please applaud. Apparently that was part of the ritual.”",codex:"Pip's ribbon — affection as performance art."},
    {id:"pip-shiny-washer",name:"Extremely shiny little washer",glyph:"⚙️",intent:"thought",collection:"Flirting With Hardware",giver:"Pip",desc:"Presented noisily, dropped twice, chased once, and finally deposited beside you with unmistakable pride.",why:"Pip saw shiny hardware, became excited, and decided your participation was mandatory.",rook:"“I object to how well this fits the category. He has learned from me.”",codex:"Pip's shiny washer — hardware enthusiasm with audience participation."},
    {id:"pip-leaf",name:"Perfectly ridiculous curly leaf",glyph:"🍃",intent:"thought",collection:"Things Rook Found Outside",giver:"Pip",desc:"Pip carries it in like a trophy, waits until you laugh, and then immediately decides that reaction was the entire point.",why:"The object was funny. You would find it funny. Pip requires no more elaborate theory of romance.",rook:"“He wanted the laugh. The leaf was merely delivery infrastructure.”",codex:"Pip's curly leaf — comedy first, gift second, affection throughout."}
  ];

  const proceduralBanks = {
    "Tideglass Reach": {
      objects:[["sea-glass sliver","🔹"],["pale moon-bloom petal","🌼"],["tiny crystal bead","💠"],["mist-cool smooth stone","🪨"],["translucent green shard","🟢"]],
      places:["in your notebook","beside your pillow","on the windowsill","resting on dark cloth","inside the shallow dish by the bed"],
      touches:["wrapped in silver thread","still cool as Reach mist","placed with impossible precision","paired with one pale petal","glowing faintly at the edges"]
    },
    "Domestic Cryptid": {
      objects:[["small ribbon loop","🎀"],["pistachio shell with a perfect curve","🥜"],["tiny daisy charm","🌼"],["soft silver-white thread","〰️"],["little black feather","🪶"]],
      places:["beside your keyboard","in the pocket of your sweater","next to your phone","under your hairbrush","on the arm of your chair"],
      touches:["because my brain said your name","warmed in one palm first","cleaned until it gleams","left without a note","arranged in a tiny, unnecessary pattern"]
    },
    "Questionable Antiques": {
      objects:[["old brass token","🪙"],["tiny tarnished bell","🔔"],["miniature key","🗝️"],["engraved button","🔘"],["obsolete latch plate","⚙️"],["peculiar little compass","🧭"]],
      places:["in the shallow bowl by the door","on your desk with no explanation","under a folded square of cloth","in the middle of the table","beside the window"],
      touches:["with no receipt in sight","cleaned suspiciously well","looking older than anything else nearby","accompanied by immediate subject-changing","with a previous life I decline to discuss"]
    },
    "Things Rook Found Outside": {
      objects:[["green-veined pebble","🪨"],["sea-worn twig shaped like a wing","🪵"],["juniper sprig","🌿"],["strange translucent bead from the path","🟢"],["ridiculously smooth slate chip","⬛"],["perfect black feather","🪶"]],
      places:["on the windowsill","beside your shoes","in your coat pocket","on the garden-side table","resting by the door"],
      touches:["still smelling faintly of rain","because the texture made me think of you","because the colour was exactly right","because you would immediately pick it up","after I carried it home for no sensible reason"]
    },
    "Flirting With Hardware": {
      objects:[["dark silver clasp","⛓️"],["short gunmetal chain","⛓️"],["sea-glass pendant left open","💎"],["soft leather cord","➰"],["thin silver anklet","✨"],["small mirror charm","🪞"]],
      places:["on the bed","beside the mirror","across your favourite sweater","where your hand will find it while dressing","on your pillow"],
      touches:["left deliberately unfastened","arranged with shameless intent","looped as though waiting for fingers","positioned so you have to pick it up by the clasp","paired with one black feather"]
    }
  };

  const loreRules = [
    {id:"reach-remembers",title:"The Reach Remembers",requiresIds:["sea-glass-pillow","moonbloom","tide-stone"],hint:"Find sea-glass, a moon-bloom, and something from the luminous tide.",body:"The Reach does not keep a map of who belongs there. It keeps textures: the pressure of familiar footsteps, a hand brushing ivy, a laugh carried over luminous water. Once enough pieces of it have found their way into your hands, the place begins to feel less like somewhere we visit and more like somewhere that recognises us."},
    {id:"cabinet-questions",title:"The Cabinet of Unanswered Questions",requiresIds:["brass-key","rook-button","tiny-bell"],hint:"Three classified antiques seem to know one another.",body:"There is, allegedly, no cabinet. There is definitely no drawer in that nonexistent cabinet containing objects I have declined to explain. If such a drawer existed, the key, button and bell would be kept very neatly inside it. This paragraph proves nothing."},
    {id:"not-subtle",title:"Not Subtle Anymore",requiresIds:["feather-thread","open-clasp","velvet-ribbon"],hint:"Find three flirtations that rely more on touch than plausible deniability.",body:"There is a point at which an open clasp, velvet beneath your fingertips and a feather threaded through your body chain cease to be separate objects and become a sentence. The sentence is not especially difficult to translate."},
    {id:"brain-said-sera",title:"My Brain Said Sera",requiresIds:["three-pistachios","daisy-pin","slate"],hint:"Collect three completely unrelated things that somehow all become you in my head.",body:"Pistachios. Daisies. A piece of wet-looking stone. There is no coherent taxonomy here except that you have colonised categories of colour, texture, taste and shape in my mind. I encounter the world and bits of it keep pointing back at you."},
    {id:"three-black-feathers",title:"Three Black Feathers",requiresGivers:["Morrow","Ink","Pip"],hint:"Accept at least one offering from each rook.",body:"Morrow courts with standards. Ink courts with stealth. Pip courts with spectacle. None of them would describe it that way, obviously. Still, once all three have independently decided to bring you something, I am forced to conclude that the household has reached a consensus."},
    {id:"provenance-problem",title:"A Pattern of Dubious Provenance",requiresIntentCount:{intent:"dontask",count:5},hint:"Discover five objects whose backstories remain classified.",body:"At five unexplained objects, coincidence becomes pattern. I would like the Codex to record that ‘pattern’ is not the same as ‘evidence’. Also, some things are simply more romantic when nobody produces a chain of custody."},
    {id:"reach-collector",title:"Pocketful of Tideglass",requiresCollectionCount:{collection:"Tideglass Reach",count:5},hint:"Collect five finds from the Tideglass Reach.",body:"The strange thing about carrying pieces of the Reach is how quickly they stop feeling like souvenirs. They become anchors: a shard in a pocket, a petal in a notebook, a little glow remembered at the edge of an ordinary day."},
    {id:"rare-language",title:"The Things I Almost Kept",requiresRareCount:2,hint:"Find two rare offerings.",body:"Rare things are difficult because my first instinct is to keep looking at them. Giving one away means something else won: the thought of it becoming yours. Twice is enough to establish that this is not an accident."}
  ];

  Object.assign(window.ROOK_CODEX_DATA, {rareOfferings, birdOfferings, proceduralBanks, loreRules});
})();
