// Illustrated offerings, keyed by canonical offering id. Loaded by the page and the
// service worker (which precaches every file). Offerings without an entry keep their glyph.
// Prompts for the SpriteCook art: assets/tideglass/offering-prompts.json
globalThis.TIDEGLASS_OFFERING_ART = {
  "moonbloom": "assets/tideglass/flower_ornament.png",
  "three-pistachios": "assets/tideglass/offering_three_pistachios.png",
  "sea-glass-pillow": "assets/tideglass/offerings/sea-glass-pillow.webp",
  "tide-stone": "assets/tideglass/offerings/tide-stone.webp",
  "lantern-shard": "assets/tideglass/offerings/lantern-shard.webp",
  "daisy-pin": "assets/tideglass/offerings/daisy-pin.webp",
  "warm-stone": "assets/tideglass/offerings/warm-stone.webp",
  "hair-ribbon": "assets/tideglass/offerings/hair-ribbon.webp",
  "sweater-thread": "assets/tideglass/offerings/sweater-thread.webp",
  "brass-key": "assets/tideglass/offerings/brass-key.webp",
  "rook-button": "assets/tideglass/offerings/rook-button.webp",
  "tiny-bell": "assets/tideglass/offerings/tiny-bell.webp",
  "old-map": "assets/tideglass/offerings/old-map.webp",
  "tiny-compass": "assets/tideglass/offerings/tiny-compass.webp",
  "slate": "assets/tideglass/offerings/slate.webp",
  "juniper": "assets/tideglass/offerings/juniper.webp",
  "sea-worn-wood": "assets/tideglass/offerings/sea-worn-wood.webp",
  "white-pebble": "assets/tideglass/offerings/white-pebble.webp",
  "black-feather": "assets/tideglass/offerings/black-feather.webp",
  "feather-thread": "assets/tideglass/offerings/feather-thread.webp",
  "open-clasp": "assets/tideglass/offerings/open-clasp.webp",
  "velvet-ribbon": "assets/tideglass/offerings/velvet-ribbon.webp",
  "mirror-chain": "assets/tideglass/offerings/mirror-chain.webp",
  "silver-anklet": "assets/tideglass/offerings/silver-anklet.webp",
  "rare-first-light": "assets/tideglass/offerings/rare-first-light.webp",
  "rare-moonbloom-seed": "assets/tideglass/offerings/rare-moonbloom-seed.webp",
  "rare-double-feather": "assets/tideglass/offerings/rare-double-feather.webp",
  "rare-pocket-watch": "assets/tideglass/offerings/rare-pocket-watch.webp",
  "rare-green-opal": "assets/tideglass/offerings/rare-green-opal.webp",
  "rare-locket": "assets/tideglass/offerings/rare-locket.webp",
  "rare-chain-crescent": "assets/tideglass/offerings/rare-chain-crescent.webp",
  "rare-rook-token": "assets/tideglass/offerings/rare-rook-token.webp",
  "morrow-silver-thread": "assets/tideglass/offerings/morrow-silver-thread.webp",
  "morrow-green-stone": "assets/tideglass/offerings/morrow-green-stone.webp",
  "morrow-button": "assets/tideglass/offerings/morrow-button.webp",
  "ink-hair-tie": "assets/tideglass/offerings/ink-hair-tie.webp",
  "ink-paper-star": "assets/tideglass/offerings/ink-paper-star.webp",
  "ink-key": "assets/tideglass/offerings/ink-key.webp",
  "pip-ribbon": "assets/tideglass/offerings/pip-ribbon.webp",
  "pip-shiny-washer": "assets/tideglass/offerings/pip-shiny-washer.webp",
  "pip-leaf": "assets/tideglass/offerings/pip-leaf.webp"
};
